### ISSUE TITLE
Brak reakcji kalkulatora na klawisze klawiatury 

### ISSUE THREAD

**Issue by ttk0721** [aimeiz/Kalkulator#2]
kalkulator nie reaguje na wciśnięcia cyfr na klawiaturze, nie reaguje też na znaki specjalne. Wciskanie cyfr i znaków myszką jest uciążliwe.

**Comment by aimeiz** [comment]
Dziękuję za uwagę.
W tej wersji kalkulator działa na cyfry znak działań z numerycznego bloku klawiatury, oraz na klawisz Enter (też z bloku) i ten klawisz jest równoważny przyciskowi "="
